"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, BookOpen, Building2, LibraryBig, Pencil, Plus, Send, UserPlus } from "lucide-react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
import { sanitizeStorageName } from "@/lib/portfolio-policy";

type Family = { id: string; name: string; city: string | null; status?: string };
type Student = { id: string; family_id: string; full_name: string; birth_year: number | null; stage: string | null; status?: string };
type Area = { id: string; name: string };
type Topic = { id: string; area_id: string; name: string };
type Guide = { id: string; area_id: string; topic_id: string | null; title: string; objective: string; age_range: string; materials: string[]; steps: string[]; evidence_prompt: string; status?: string };
type Material = { id: string; title: string; description: string; category: string | null; kind: string | null; area_id?: string; topic_id?: string; source_name: string; audience: string; external_url: string; access_notes: string; storage_path?: string; status?: string };

export function AdminOperations({ families, students, areas, topics, guides, resources }: { families: Family[]; students: Student[]; areas: Area[]; topics: Topic[]; guides: Guide[]; resources: Material[] }) {
  const [tab, setTab] = useState<"people" | "content">("people");
  return <div className="rounded-lg border border-ink/8 bg-white p-5 shadow-line">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase text-teal">Administración</p><h2 className="mt-1 text-xl font-semibold">Control operativo</h2></div><div className="flex rounded-md bg-cloud p-1"><button onClick={() => setTab("people")} className={`rounded px-3 py-2 text-sm font-semibold ${tab === "people" ? "bg-white text-forest shadow" : "text-ink/55"}`}>Familias y alumnos</button><button onClick={() => setTab("content")} className={`rounded px-3 py-2 text-sm font-semibold ${tab === "content" ? "bg-white text-forest shadow" : "text-ink/55"}`}>Guías y materiales</button></div></div>
    {tab === "people" ? <PeopleAdmin families={families} students={students} /> : <ContentAdmin areas={areas} topics={topics} guides={guides} resources={resources} />}
  </div>;
}

function PeopleAdmin({ families, students }: { families: Family[]; students: Student[] }) {
  const router = useRouter(); const [editFamily, setEditFamily] = useState<Family | null>(null); const [editStudent, setEditStudent] = useState<Student | null>(null); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>, entity: "family" | "student") { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const payload = entity === "family" ? { entity, action: editFamily ? "update" : "create", id: editFamily?.id, name: data.get("name"), city: data.get("city"), notes: data.get("notes") } : { entity, action: editStudent ? "update" : "create", id: editStudent?.id, familyId: data.get("familyId"), fullName: data.get("fullName"), birthYear: data.get("birthYear") ? Number(data.get("birthYear")) : null, stage: data.get("stage"), notes: data.get("notes") }; if (await send(payload, setMessage)) { form.reset(); setEditFamily(null); setEditStudent(null); router.refresh(); } }
  async function archive(entity: "family" | "student", id: string) { if (!window.confirm("El registro dejará de aparecer en las vistas operativas. ¿Continuar?")) return; if (await send({ entity, action: "archive", id }, setMessage)) router.refresh(); }
  return <div className="mt-5 grid gap-5 xl:grid-cols-2">
    <section><div className="flex items-center gap-2"><Building2 className="h-5 w-5 text-forest" /><h3 className="font-semibold">Familias</h3></div><form key={editFamily?.id || "new-family"} onSubmit={(e) => submit(e, "family")} className="mt-3 grid gap-3 rounded-lg bg-cloud p-4"><input name="name" required defaultValue={editFamily?.name} className="input" placeholder="Nombre de familia" /><input name="city" defaultValue={editFamily?.city || ""} className="input" placeholder="Ciudad" /><textarea name="notes" className="input" rows={2} placeholder="Notas internas" /><div className="flex gap-2"><button className="inline-flex items-center gap-2 rounded-md bg-forest px-4 py-2 text-sm font-semibold text-white">{editFamily ? <Pencil className="h-4 w-4" /> : <Plus className="h-4 w-4" />}{editFamily ? "Guardar" : "Crear familia"}</button>{editFamily ? <button type="button" onClick={() => setEditFamily(null)} className="rounded-md border px-3 text-sm font-semibold">Cancelar</button> : null}</div></form><div className="mt-3 grid gap-2">{families.map((family) => <Row key={family.id} title={family.name} subtitle={family.city || "Sin ciudad"} onEdit={() => setEditFamily(family)} onArchive={() => archive("family", family.id)} />)}</div></section>
    <section><div className="flex items-center gap-2"><UserPlus className="h-5 w-5 text-teal" /><h3 className="font-semibold">Alumnos</h3></div><form key={editStudent?.id || "new-student"} onSubmit={(e) => submit(e, "student")} className="mt-3 grid gap-3 rounded-lg bg-cloud p-4"><select name="familyId" required disabled={Boolean(editStudent)} defaultValue={editStudent?.family_id || ""} className="input"><option value="">Selecciona familia</option>{families.map((family) => <option key={family.id} value={family.id}>{family.name}</option>)}</select><input name="fullName" required defaultValue={editStudent?.full_name} className="input" placeholder="Nombre completo" /><div className="grid grid-cols-2 gap-2"><input name="birthYear" type="number" min={2015} max={2035} defaultValue={editStudent?.birth_year || ""} className="input" placeholder="Año nacimiento" /><input name="stage" defaultValue={editStudent?.stage || "3-6 años"} className="input" placeholder="Etapa" /></div><textarea name="notes" className="input" rows={2} placeholder="Notas internas" /><div className="flex gap-2"><button className="inline-flex items-center gap-2 rounded-md bg-forest px-4 py-2 text-sm font-semibold text-white">{editStudent ? "Guardar" : "Crear alumno"}</button>{editStudent ? <button type="button" onClick={() => setEditStudent(null)} className="rounded-md border px-3 text-sm font-semibold">Cancelar</button> : null}</div></form><div className="mt-3 grid gap-2">{students.map((student) => <Row key={student.id} title={student.full_name} subtitle={`${families.find((f) => f.id === student.family_id)?.name || "Familia"} · ${student.stage || "Etapa abierta"}`} onEdit={() => setEditStudent(student)} onArchive={() => archive("student", student.id)} />)}</div></section>
    {message ? <p className="rounded bg-cloud px-3 py-2 text-sm xl:col-span-2">{message}</p> : null}
  </div>;
}

function ContentAdmin({ areas, topics, guides, resources }: { areas: Area[]; topics: Topic[]; guides: Guide[]; resources: Material[] }) {
  const router = useRouter(); const [editGuide, setEditGuide] = useState<Guide | null>(null); const [editMaterial, setEditMaterial] = useState<Material | null>(null); const [message, setMessage] = useState("");
  async function submitGuide(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); const payload = { entity: "guide", action: editGuide ? "update" : "create", id: editGuide?.id, areaId: d.get("areaId"), topicId: d.get("topicId"), title: d.get("title"), objective: d.get("objective"), ageRange: d.get("ageRange"), materials: lines(d.get("materials")), steps: lines(d.get("steps")), evidencePrompt: d.get("evidencePrompt") }; if (await send(payload, setMessage)) { form.reset(); setEditGuide(null); router.refresh(); } }
  async function submitMaterial(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const d = new FormData(form); const resourceFile = d.get("resourceFile"); let storagePath: string | undefined; if (resourceFile instanceof File && resourceFile.size) { if (resourceFile.size > 10 * 1024 * 1024 || !["application/pdf", "image/jpeg", "image/png", "image/webp"].includes(resourceFile.type)) { setMessage("El material debe ser PDF, JPG, PNG o WebP de hasta 10 MB."); return; } const supabase = createBrowserSupabaseClient(); if (!supabase) { setMessage("Supabase no está configurado."); return; } storagePath = `global/${crypto.randomUUID()}-${sanitizeStorageName(resourceFile.name)}`; setMessage("Subiendo archivo privado…"); const { error } = await supabase.storage.from("resource-files").upload(storagePath, resourceFile, { contentType: resourceFile.type }); if (error) { setMessage("No pudimos subir el archivo del material."); return; } } const payload = { entity: "material", action: editMaterial ? "update" : "create", id: editMaterial?.id, areaId: d.get("areaId"), topicId: d.get("topicId"), title: d.get("title"), description: d.get("description"), category: d.get("category"), kind: d.get("kind"), sourceName: d.get("sourceName"), audience: d.get("audience"), externalUrl: d.get("externalUrl"), accessNotes: d.get("accessNotes"), ...(storagePath ? { storagePath } : {}) }; if (await send(payload, setMessage)) { form.reset(); setEditMaterial(null); router.refresh(); } else if (storagePath) { await createBrowserSupabaseClient()?.storage.from("resource-files").remove([storagePath]); } }
  async function status(entity: "guide" | "material", action: "publish" | "archive", id: string) { if (await send({ entity, action, id }, setMessage)) router.refresh(); }
  return <div className="mt-5 grid gap-5 xl:grid-cols-2">
    <section><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-forest" /><h3 className="font-semibold">Guías</h3></div><form key={editGuide?.id || "new-guide"} onSubmit={submitGuide} className="mt-3 grid gap-3 rounded-lg bg-cloud p-4"><input name="title" required defaultValue={editGuide?.title} className="input" placeholder="Título" /><select name="areaId" required defaultValue={editGuide?.area_id || ""} className="input"><option value="">Área</option>{areas.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="topicId" defaultValue={editGuide?.topic_id || ""} className="input"><option value="">Submateria general</option>{topics.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><textarea name="objective" required defaultValue={editGuide?.objective} className="input" placeholder="Objetivo" /><input name="ageRange" defaultValue={editGuide?.age_range || "3-6 años"} className="input" /><textarea name="materials" defaultValue={editGuide?.materials.join("\n")} className="input" rows={3} placeholder="Un material por línea" /><textarea name="steps" defaultValue={editGuide?.steps.join("\n")} className="input" rows={4} placeholder="Un paso por línea" /><textarea name="evidencePrompt" defaultValue={editGuide?.evidence_prompt} className="input" placeholder="Evidencia sugerida" /><SaveButtons editing={Boolean(editGuide)} cancel={() => setEditGuide(null)} /></form><div className="mt-3 grid gap-2">{guides.map((g) => <ContentRow key={g.id} title={g.title} status={g.status} onEdit={() => setEditGuide(g)} onPublish={() => status("guide", "publish", g.id)} onArchive={() => status("guide", "archive", g.id)} />)}</div></section>
    <section><div className="flex items-center gap-2"><LibraryBig className="h-5 w-5 text-teal" /><h3 className="font-semibold">Materiales</h3></div><form key={editMaterial?.id || "new-material"} onSubmit={submitMaterial} className="mt-3 grid gap-3 rounded-lg bg-cloud p-4"><input name="title" required defaultValue={editMaterial?.title} className="input" placeholder="Título" /><textarea name="description" defaultValue={editMaterial?.description} className="input" placeholder="Descripción" /><select name="areaId" defaultValue={editMaterial?.area_id || ""} className="input"><option value="">Área general</option>{areas.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="topicId" defaultValue={editMaterial?.topic_id || ""} className="input"><option value="">Submateria general</option>{topics.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input name="category" defaultValue={editMaterial?.category || ""} className="input" placeholder="Categoría" /><input name="kind" defaultValue={editMaterial?.kind || ""} className="input" placeholder="Tipo" /></div><input name="sourceName" defaultValue={editMaterial?.source_name} className="input" placeholder="Fuente" /><input name="audience" defaultValue={editMaterial?.audience} className="input" placeholder="Audiencia" /><input name="externalUrl" type="url" defaultValue={editMaterial?.external_url} className="input" placeholder="Enlace HTTPS" /><label className="grid gap-1 text-sm font-semibold">Archivo privado opcional<input name="resourceFile" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="input" /></label><textarea name="accessNotes" defaultValue={editMaterial?.access_notes} className="input" placeholder="Notas de acceso" /><SaveButtons editing={Boolean(editMaterial)} cancel={() => setEditMaterial(null)} /></form><div className="mt-3 grid gap-2">{resources.map((r) => <ContentRow key={r.id} title={r.title} status={r.status} onEdit={() => setEditMaterial(r)} onPublish={() => status("material", "publish", r.id)} onArchive={() => status("material", "archive", r.id)} />)}</div></section>
    {message ? <p className="rounded bg-cloud px-3 py-2 text-sm xl:col-span-2">{message}</p> : null}
  </div>;
}

function Row({ title, subtitle, onEdit, onArchive }: { title: string; subtitle: string; onEdit: () => void; onArchive: () => void }) { return <div className="flex items-center gap-2 rounded-md border border-ink/8 px-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{title}</p><p className="truncate text-xs text-ink/50">{subtitle}</p></div><button onClick={onEdit} className="p-2" aria-label={`Editar ${title}`}><Pencil className="h-4 w-4" /></button><button onClick={onArchive} className="p-2 text-coral" aria-label={`Archivar ${title}`}><Archive className="h-4 w-4" /></button></div>; }
function ContentRow({ title, status, onEdit, onPublish, onArchive }: { title: string; status?: string; onEdit: () => void; onPublish: () => void; onArchive: () => void }) { return <div className="flex items-center gap-2 rounded-md border border-ink/8 px-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{title}</p><p className="text-xs text-ink/50">{status || "Publicado"}</p></div><button onClick={onEdit} className="p-2"><Pencil className="h-4 w-4" /></button><button onClick={onPublish} className="p-2 text-forest" title="Publicar"><Send className="h-4 w-4" /></button><button onClick={onArchive} className="p-2 text-coral"><Archive className="h-4 w-4" /></button></div>; }
function SaveButtons({ editing, cancel }: { editing: boolean; cancel: () => void }) { return <div className="flex gap-2"><button className="rounded-md bg-forest px-4 py-2 text-sm font-semibold text-white">{editing ? "Guardar" : "Crear borrador"}</button>{editing ? <button type="button" onClick={cancel} className="rounded-md border px-3 text-sm font-semibold">Cancelar</button> : null}</div>; }
function lines(value: FormDataEntryValue | null) { return String(value || "").split("\n").map((line) => line.trim()).filter(Boolean); }
async function send(payload: Record<string, unknown>, setMessage: (value: string) => void) { setMessage("Guardando…"); const response = await fetch("/api/dashboard/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => ({})); setMessage(response.ok ? "Cambio guardado correctamente." : result.message || "No pudimos guardar el cambio."); return response.ok; }
